### ISSUE TITLE
Compile-time weaving support for aspects

### ISSUE THREAD

**Issue by jefftap** [micrometer-metrics/micrometer#1149]
Hi, I am attempting to make use of `TimedAspect` via AspectJ compile-time weaving using the `aspectj-maven-plugin`. When the aspect code is executed, it throws one of the two errors, depending on what is being executed:

```
java.lang.NoSuchMethodError: io.micrometer.core.aop.TimedAspect.aspectOf()Lio/micrometer/core/aop/TimedAspect
```

```
java.lang.NoSuchMethodException: io.micrometer.core.aop.TimedAspect.aspectOf()
```

This usually indicates that the AspectJ weaver has not properly processed the aspect code. I am not sure if this is a problem with my own code/configuration, or if it's an issue in Micrometer's jar. The aspect works perfectly fine using Spring AOP, but I would prefer to use AspectJ weaving with `@Timed` to allow it access to private/protected methods and the other various benefits one gets from AspectJ integration.

Relevant information:
* micrometer-core version: 1.1.1
* Spring Boot version: 2.1.1.RELEASE
* AspectJ verison: 1.9.2
* Java version: 1.8
* aspectj-maven-plugin version: 1.11

aspectj-maven-plugin configuration:
```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>1.11</version>
                <configuration>
                    <complianceLevel>1.8</complianceLevel>
                    <source>1.8</source>
                    <target>1.8</target>
                    <showWeaveInfo>true</showWeaveInfo>
                    <Xlint>ignore</Xlint>
                    <aspectLibraries>
                        <aspectLibrary>
                            <groupId>org.springframework</groupId>
                            <artifactId>spring-aspects</artifactId>
                        </aspectLibrary>
                        <aspectLibrary>
                            <groupId>io.micrometer</groupId>
                            <artifactId>micrometer-core</artifactId>
                        </aspectLibrary>
                    </aspectLibraries>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

```

**Comment by jkschneider** [comment]
Have you added aspectj weaving to the build section of your POM?

```
<build>
<plugins>
  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>aspectj-maven-plugin</artifactId>
    <executions>
      <execution>
        <goals>
          <goal>compile</goal> 
        </goals>
      </execution>
    </executions>
  </plugin>
</plugins>
```

**Comment by jefftap** [comment]
Yes. The aspectj-maven-plugin configuration I posted in my initial post is under `<build>/<plugins>`.

**Comment by jefftap** [comment]
Also, one way to work around this is to write your own aspect that weaves around an annotation and use the `Timer` methods in there. It still needs to be coupled with Spring, though. Inject the `MeterRegistry` as a dependency. The bean should be declared in the Spring configuration using the `Aspects.aspectOf` method to pull in the AspectJ instance, and Spring handles the injection from there.

**Comment by izeye** [comment]
I don't have much expertise on AspectJ but after some quick research, it seems to require a similar configuration to [`spring-aspects`](https://github.com/spring-projects/spring-framework/blob/master/spring-aspects/spring-aspects.gradle) to support compile-time weaving as already pointed out by @jefftap although I'm not sure there's any plan for compile-time weaving support.

**Comment by jefftap** [comment]
Looks like spring-aspects.jar compiles with ajc, then.  I think the solution to this ticket is to either compile Micrometer with ajc, or improve the documentation on how to get Micrometer to work properly with AspectJ. I can write a small addition to the documentation explaining this, if desired.

**Comment by ewencluley-bw** [comment]
I am running into the exact same issue as @jefftap. While the compile time weaving seems to succeed, at runtime the aspectOf methods are not there on the `TimedAspect` classes.  The documentation for micrometer suggests the `@Timed` annotation should be supported using compile time aspectj weaving. (https://micrometer.io/docs/concepts#_the_code_timed_code_annotation)
> use in your application either through compile/load time AspectJ weaving or through framework facilities that interpret AspectJ aspects

Would be great to have some documentation on how to get this working.

**Comment by Phil-Ba** [comment]
I didn't manage to get this working with CTW. As far as I understood it, it seems that micrometer-core is not compiled with the ajc and thus the aspects are missing the required factory methods.
The only solution I found, was to do LTW and have the micrometer-core classes also be woven during load time.
Another solution would be the recompile the micrometer-core jar with the aspectj maven plugin, but this also requires all dependencies...

**Comment by Exidex** [comment]
The issue still persist. As noted higher it could be resolved by using LTW, but in my case it is not an option because I do not have access to the deployment setup, and the only option is CTW which doesn't work with this library

**Comment by venushka** [comment]
I've had the same issue with CTW, although I got around this by extending the aspect like this for now.
```
@Aspect
public class MetricsAspect {
  @Around("execution (@io.micrometer.core.annotation.Timed * *.*(..))")
  public Object timedMethod(ProceedingJoinPoint pjp) throws Throwable {
    final TimedAspect timeAspect = new TimedAspect(MetricsServlet.getRegistry());
    return timeAspect.timedMethod(pjp);
  }
}
```
and adding the following to the aop.xml
```
<aspectj>
  <aspects>
    <aspect name="com.venushka.metrics.MetricsAspect"/>
  </aspects>
</aspectj>
```
It would be great if this works out of the box for CTW.

**Comment by dalbani** [comment]
Hi, for those on the interweb who came here for load time weaving (LTW), I confirm that it works.
That's my `META-INF/aop.xml` file:
```xml
<aspectj>
    <weaver>
        <include within="io.micrometer.core..*"/>
        <include within="my.app..*"/>
    </weaver>

    <aspects>
        <aspect name="io.micrometer.core.aop.TimedAspect"/>
    </aspects>
</aspectj>
```

To be used in conjunction with a class like:
```java
package my.app;

public class App {
  @Timed("xyz")
  public void fun1() { }
}
```
In a Spring Boot application with the `@EnableLoadTimeWeaving` annotation.

I'm a newbie when it comes to aspects, but I'm wondering what the advantages of CTW over LTW are.
@Exidex: when you said that "you do not have access to the deployment setup", did you mean that you couldn't make sure that the JVM was configured with the appropriate agent?
I don't know if that would solve your problem, but I personally use <https://github.com/invesdwin/invesdwin-instrument> to have the application code register the agent by itself.

**Comment by kriegaex** [comment]
Because I often answer questions on StackOverflow, I found this issue, not for the first time in the last few years. Today I took some time to look into it, producing a little example project, showing how to apply `TimedAspect` via `@Timed ` via compile-time weaving with AspectJ Maven plugin. The same basic approach should also work with Gradlle, but I am a Maven guy.

https://github.com/kriegaex/SO_AJ_MicrometerTimed_67803726

The project simply consists of one class and a POM + an explanatory read-me file. The gist of it is: You must make sure to apply binary weaving the the Micrometer aspect in order to transform it into a real AspectJ aspect, and then apply that aspect to your own project.

**Comment by marcingrzejszczak** [comment]
Since there are ways of how to achieve this is there anything else we should do here, other than maybe document this?

**Comment by kriegaex** [comment]
> Since there are ways of how to achieve this

My workaround is very contrived. IMO, it is unreasonable to assume that any normal user who does not happen to be an AspectJ expert can find out how to do this. Even if it was documented, users would be doing the Micrometer team's work there.

> is there anything else we should do here, other than maybe document this?

Yes, add an Aspectj compilation step to the Gradle build (e.g. using Freefair plugin) and make sure that what is advertised as an **AspectJ aspect**, ...

https://github.com/micrometer-metrics/micrometer/blob/225234755f1ad70cd67eea167862c1cedddc0cd2/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L36-L37

... does actually really deserve its name and incomplete non-AspectJ compilation with Javac needs to be finished by the user. That this happens to work with LTW, because the AspectJ weaver is smart enough to notice and finish the job, does not mean that CTW is some kind of second-class citizen. Make your product easy to use. The correctly compiled aspect would, of course, still work with LTW. With CTW, the library could just be put on the _aspectpath_, as is customary. No extra build steps or extra modules, creating a refined version of this library as an input for later steps.

Of course, `aspectjrt` would become a dependency of this library, but in fact it already is anyway, because as-is, you need LTW and `aspectjweaver`, which is a superset of `aspectjrt`. This dependency should be clearly documented simply by declaring it as such.

**Comment by mihalyr-prospect** [comment]
I am trying to migrate my project from Dropwizard Metrics to Micrometer and I'm blocked on this issue as I am trying to use compile-time weaving just like with Dropwizard annotations before and it doesn't seem to work with Micrometer despite the documentation saying it can be used also with compile time weaving. 

I have a Gradle project and was trying to convert the above mentioned workaround from Maven to Gradle, but the plugins are different and am running into various build failures. I tried to revert to Spring AOP proxies, but that doesn't work on my project, CGLIB breaking some of the classes. 

Are there any updates on the fix? Or did anyone make it work with Gradle (Freefair plugin)?

**Comment by kriegaex** [comment]
@marcingrzejszczak, see, this is what I mean. It is possible to finish the unfinished job my Micrometer manually as a user, but it is not trivial. Instead of burdening users, trying to figure out how to use your aspect, because you think it is unnecessary to compile it with the AspectJ compiler, you should finally get this issue off the table. Or are you expecting me to convert my Maven solution to Gradle on behalf of @mihalyr-prospect?

**Comment by marcingrzejszczak** [comment]
@kriegaex I don't think that your answer is nice or brings any value to this discussion. We will take care of this issue whenever we have bandwith to do so.

**Comment by kriegaex** [comment]
@marcingrzejszczak: I wanted to be clear rather than nice. I was not nice, maybe, but also not non-nice. I did not insult anyone. Honestly, this issue has been open for more than 5 years, and I do not really buy the bandwidth argument, because
  * your product is an aspect library, but you do compile the aspect as such,
  * which makes this issue a high priority one, IMO,
  * it is clear what needs to be done, no further debugging or even any code changes necessary,
  * changing the build configuration should be straightforward and in no way rocket science.

The product I maintain, AspectJ, is a cornerstone of Micrometer, so please understand that I would rather see it fixed than feeling compelled to devise custom workarounds to various users for a few more years.

**Comment by marcingrzejszczak** [comment]
If you want to push this forward do you care for a PR? We're not experts on aspects and I do not agree that "your product is an aspect library". Micrometer happens to have an aspect but it's an observation library so help from such a distinguished engineer as yourself, the maintainer of AspectJ, in a form of a PR would be invaluable.

**Comment by kriegaex** [comment]
I already created a humble bit of value by contributing a workaround ~4 years ago in https://github.com/micrometer-metrics/micrometer/issues/1149#issuecomment-855193945. I might have contributed a PR already, if the Micrometer build was Maven and not Gradle, which I barely speak.

I also wanted to avoid repeating bad experience from many other OSS projects I contributed to, namely long-winded code review processes in which I felt like a remote-controlled puppet rather than a contributor. Of course, the experience here could me much better, but I have no way of knowing.

**Comment by kriegaex** [comment]
@marcingrzejszczak, I wasted more than an hour, trying to get the Freefair plugin into this complex multi-module configuration, but it is beyond me how to do that without lots of errors. I am giving up. Someone who knows both Gradle and this product needs to do that, I can only support explaining what basically needs to be done. Like I said, I am a Maven guy, Gradle is a nightmare to me.

**Comment by marcingrzejszczak** [comment]
> Like I said, I am a Maven guy, Gradle is a nightmare to me.

I fully understand. Same here, Gradle is a nightmare for me too ;)

So if I understand correctly it's enough to "add an AspectJ compilation step to the Gradle build (e.g. using Freefair plugin)" ? How can we then test that?

**Comment by mihalyr** [comment]
Hey guys, I am also not that well versed with Gradle but put an small example together, this works for me locally https://github.com/mihalyr/micrometer/commit/ee9c36b730f07c404507e72aab48aa295e3e9e4c (test included)

**Comment by mihalyr** [comment]
Thank you, I submitted a PR to fix the pointcut syntax https://github.com/micrometer-metrics/micrometer/pull/5058 and also updated my example code with it https://github.com/mihalyr/micrometer/commit/af59da954e4980cb1577b80a3915a4154bcb32d7

**Comment by marcingrzejszczak** [comment]
I've drafted a solution basing on @mihalyr suggestion but since I'm no expert with AspectJ I can't make the tests pass. Apparently I can't make our previous tests pass with the new setup. It seems that the default Spring setup doesn't like AJC compiled classes.

I've asked for help on the spring framework channel but in the meantime I'll ping @aclement and @jhoeller. Also @kriegaex help would be invaluable.

**Comment by mihalyr** [comment]
@marcingrzejszczak the build in your PR shows a checkstyle failure not a test issue https://ge.micrometer.io/s/sor5zjauvpeim

```
[ant:checkstyle] [ERROR] /home/circleci/micrometer/micrometer-observation/src/test/resources/META-INF/aop.xml:1:50: http:// URLs are not allowed but got 'http://www.eclipse.org/aspectj/dtd/aspectj.dtd'. Use https:// instead. [NoHttp]
```

It seems your project doesn't like HTTP URLs in files. You can try using an HTTPS URL or drop the DOCTYPE from `aop.xml`, it's not required.

**Comment by mihalyr** [comment]
but your JDK11 build won't compile, it seems the AspectJ version there requires JDK17

```
 > Task :micrometer-observation:compileJava FAILED
Exception in thread "main" Message: null
org.aspectj.bridge.AbortException: The AspectJ compiler needs at least Java runtime 17
        at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
        at org.aspectj.tools.ajc.Main.main(Main.java:92)
```

**Comment by marcingrzejszczak** [comment]
I've ran the build locally and I had jdk17 and it didn't run checkstyle so that wasn't a problem for me. Thanks for pointing it out though, I'll update the branch. The problem I had was related to tests failing.

**Comment by kriegaex** [comment]
Since 1.9.8, the AspectJ compiler needed JDK 11+ during build time, since 1.9.21 JDK JDK 17+, see

* https://github.com/eclipse-aspectj/aspectj/blob/master/docs/release/JavaVersionCompatibility.adoc
* https://github.com/eclipse-aspectj/aspectj/blob/master/docs/release/README-1.9.22.adoc#aspectj-compiler-build-system-requirements

Source/target 8 is no üproblem, but due to AspectJ's dependency on the Eclipse Java Compiler, we have to follow their requirements. But that only affects the build system, not the runtimne or load-time weaver.

**Comment by kriegaex** [comment]
@marcingrzejszczak, which tests are failing?

**Comment by kriegaex** [comment]
As for HTTP URLs in _aop.xml_, simply use https://eclipse.dev/aspectj/dtd/aspectj.dtd etc. instead.

**Comment by marcingrzejszczak** [comment]
> As for HTTP URLs in aop.xml, simply use https://eclipse.dev/aspectj/dtd/aspectj.dtd etc. instead.

Yeah I fixed that and all the other checkstyle issues.

> @marcingrzejszczak, which tests are failing?

So I'm in touch with @jhoeller because apparently Spring doesn't work with `@Aspect` annotated classes that have been compiled with AJC. So all of our tests that rely on Spring's proxying mechanism no longer work. Most likely we will need to relax some constraints in Spring Framework for that work but I can give the floor to Juergen to explain that in more details :)

**Comment by kriegaex** [comment]
> apparently Spring doesn't work with `@Aspect` annotated classes that have been compiled with AJC

Oh, really? Too bad. I would like to try for myself and find out why that might be the case. Or maybe @jhoeller can explain why.

**Comment by mihalyr** [comment]
Hey guys, I think we can first fix LTW which also has some problems with the class-level annotations not working. I have addressed those in https://github.com/micrometer-metrics/micrometer/pull/5060 and also provided a test for LTW. 

This works for both the existing Spring AOP proxies and LTW. Once this is in, we can add CTW on top of it easier. What do you think?

**Comment by mihalyr** [comment]
@kriegaex I also reproduced the error Marcin was talking about

```
TimedAspectTest > timeMethod() FAILED
    org.springframework.aop.framework.AopConfigException: Advice must be declared inside an aspect type: Offending method 'public java.lang.Object io.micrometer.core.aop.TimedAspect.timedClass(org.aspectj.lang.ProceedingJoinPoint) throws java.lang.Throwable' in class [io.micrometer.core.aop.TimedAspect]
        at app//org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvice(ReflectiveAspectJAdvisorFactory.java:254)
        at app//org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.instantiateAdvice(InstantiationModelAwarePointcutAdvisorImpl.java:150)
        at app//org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:114)
        at app//org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:213)
        at app//org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:144)
        at app//org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
        at app//org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:99)
        at app//io.micrometer.core.aop.TimedAspectTest.timeMethod(TimedAspectTest.java:51)
```

Code is in https://github.com/mihalyr/micrometer/tree/fix-aspectj-ctw on top of my LTW fix from #5060

**Comment by jhoeller** [comment]
See https://github.com/spring-projects/spring-framework/issues/32793 - I'm going to relax that Spring AOP check for 6.1.7, scheduled for release next week. Should be available in a 6.1.7 snapshot within an hour or so.

**Comment by kriegaex** [comment]
@jhoeller, sorry for asking instead of digging into the source code, but I am neither involved in Spring nor Micrometer and a bit under time pressure today: Is that relaxed check something that could be backported to older Spring versions which still receive regular or occasional updates?

**Comment by mihalyr** [comment]
That's a good questions, because the Micrometer build seems to be using Spring 5.x too.

**Comment by jhoeller** [comment]
If there is a concrete need for upcoming Micrometer releases, we can consider backporting this to 6.0.20 and 5.3.35. It is not entirely trivial though since it involves some potential issues for mixed AspectJ usage (using different `@Aspect` aspects for proxying and weaving in the same application, with both kinds of aspects defined as Spring beans) which we need to leniently handle; that came in a follow-up commit on 6.1.7.

@marcingrzejszczak please advise how concrete the need for a backport is here.

**Comment by mihalyr** [comment]
I quickly checked the new Spring 6.1.7 snapshot on my branch, bumped compatibility to Java 17 and tests worked for Spring AOP, AspectJ LTW and CTW too. This looks like a good direction, just need to solve the compatibility issue in some way.

**Comment by jhoeller** [comment]
Thanks for the immediate check, @mihalyr! The present arrangement in 6.1.7 is good to go, there's just the question of the backports... mostly a concern with unexpected side effects in niche scenarios where we currently limit the problem to 6.1.x, unless we have a scenario where this has to work in older branches as well.

**Comment by marcingrzejszczak** [comment]
We still maintain micrometer [1.11.x](https://github.com/micrometer-metrics/micrometer/blob/1.11.x/gradle/libs.versions.toml#L71) and [1.12.x](https://github.com/micrometer-metrics/micrometer/blob/1.12.x/gradle/libs.versions.toml#L71) which both are using Spring 5.3.x. If we backported Spring Framework for this version then all of the [OSS supported](https://micrometer.io/support/) versions would be fixed

**Comment by jhoeller** [comment]
So you intend to backport the ajc compilation step to Micrometer 1.11.x and 1.12.x as well, @marcingrzejszczak? I originally assumed that would only apply to the latest branch... I guess it depends on whether you see this as an enhancement or a bug fix.

**Comment by marcingrzejszczak** [comment]
Oh yeah, that's a good question. I wouldn't say it's a bug, I'd say that's a new feature. So we could stay with the current version and release this for Micrometer 1.14.0

**Comment by kriegaex** [comment]
I also think it is an improvement rather than a bug fix, but a very useful one. Is there a strict bugfix-only policy in Micrometer?

**Comment by marcingrzejszczak** [comment]
Yeah we try to follow that rule as much as possible - features in new minors, bug fixes in patches

**Comment by kriegaex** [comment]
OK, i.e. users who want to use Micrometer with AspectJ in a CTW scenario need to use the latest version and also upgrade to Spring 6. (No need to reply, unless I am wrong.)

**Comment by marcingrzejszczak** [comment]
We can document the workaround for older versions and add this as a feature in 1.14

**Comment by kriegaex** [comment]
> We can document the workaround for older versions and add this as a feature in 1.14

If somebody knows how to do in Gradle what I suggested for Maven, yeah.

**Comment by mihalyr** [comment]
@kriegaex to make LTW/CTW work I had to make some changes to pointcuts - but I'm not that good with aspects in general, would it be possible for you to take a quick look? 

My changes are now in https://github.com/micrometer-metrics/micrometer/pull/5064 to be merged to Marcin's PR in  https://github.com/micrometer-metrics/micrometer/pull/5059

One change I had to make was to make the pointcuts match only methods and not constructors because the implementation casted the signature to MethodSignature and getting a ConstructorSignature crashed it.

This is the one for class-level annotations which should match all methods within an annotated class that are otherwise not annotated already and exclude constructors. 

```diff
-    @Around("@within(io.micrometer.core.annotation.Counted) && !@annotation(io.micrometer.core.annotation.Counted)")
+    @Around("@within(io.micrometer.core.annotation.Counted) && !@annotation(io.micrometer.core.annotation.Counted) && execution(* *(..))")
```

The other issue was with a method pointcut for which I changed the aspect method signature to make it work, but this breaks some binary compatibility checks in the project, so would be perhaps easier if we could find a fix without the method signature change if possible. Here is my change currently which works with LTW/CTW and Spring AOP too:

```diff
-    @Around(value = "@annotation(counted)", argNames = "pjp,counted")
+    @Around("execution (@io.micrometer.core.annotation.Counted * *.*(..))")
     @Nullable
-    public Object interceptAndRecord(ProceedingJoinPoint pjp, Counted counted) throws Throwable {
+    public Object interceptAndRecord(ProceedingJoinPoint pjp) throws Throwable {
```

Please let me know if there is a better way to do this.

**Comment by kriegaex** [comment]
@mihalyr, maybe we should talk (not write) one of these days, because the back-and-forth might get tedious. I need to learn more about your usage scenarios before being able to answer. For instance, I do not understand why you would need to change anything in your pointcuts for CTW in the first place. The only reason would be that that it was broken before for LTW, too, which is unrelated to this issue here. But of course, it should be fixed anyway if it is broken.

**Comment by kriegaex** [comment]
I made a quick experiment with a Spring AOP demo app and Spring 5.x, compiled with Javac, and a native AspectJ aspect compiled manually (single class file) with Ajc. It is not working due to a stacktrace like this:

```text
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myAspect' defined in file [C:\Users\Alexander\Documents\java-src\spring-aop-playground\target\classes\de\scrum_master\spring\q75728468\MyAspect.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.4.jar:2.6.4]
	at de.scrum_master.spring.q75728468.DemoApplication.main(DemoApplication.java:18) ~[classes/:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326) ~[spring-beans-5.3.16.jar:5.3.16]
	... 17 common frames omitted
Caused by: org.aspectj.lang.NoAspectBoundException: de.scrum_master.spring.q75728468.MyAspect
	at de.scrum_master.spring.q75728468.MyAspect.aspectOf(MyAspect.java:1) ~[classes/:na]
	at de.scrum_master.spring.q75728468.MyAspect.<clinit>(MyAspect.java:1) ~[classes/:na]
	... 25 common frames omitted
```

Is this the problem you guys were talking about earlier and which needs relaxing of some checks in Spring?

**Comment by mihalyr** [comment]
> For instance, I do not understand why you would need to change anything in your pointcuts for CTW in the first place. The only reason would be that that it was broken before for LTW, too, which is unrelated to this issue here.

Exactly, it was broken for LTW too. 

The annotations could be added for a whole class and for separate methods. If it is on a class, it would instrument all methods (that are otherwise not annotated with the same annotation). But this class level annotation was broken because of the `and not` syntax so the pointcut didn't work (only worked for methods). When I fixed this by changing `and not` to `&& !` the pointcut started to work but also matched constructors which the code didn't expect and crashed - both CTW and LTW. My fix for this was to add `&& execution(* *(..))` to filter out constructors, which works now. 

After all this I noticed that I get double counts using `@Counted` and the only difference between that and the other aspects was the pointcut.

Counted used: `@Around(value = "@annotation(counted)", argNames = "pjp,counted")`

While Timed used: `@Around("execution (@io.micrometer.core.annotation.Timed * *.*(..))")`

So I changed Counted also to `@Around("execution (@io.micrometer.core.annotation.Counted * *.*(..))")` and now it works fine. 

So right now with these pointcut changes everything seems to be working, AspectJ with CTW or LTW and also Spring AOP (with 6.1.7-SNAPSHOT and JDK17). 

I'm not really involved with Micrometer project though, I just wanted to use this library the first time ever and naturally went for CTW which didn't work and ended up here, found a little free time to help out, but don't know much about why things were written in a certain way or what other goals are here. For that I think Marcin is the person to ask.

**Comment by kriegaex** [comment]
Thanks for the clarification. I recommend a more readable change like this instead as a minimal and clean change comparewd to the main branch:

```java
@Around(value = "@annotation(counted) && execution(* *(..))", argNames = "pjp,counted")
```

I find that more readable, and it is a simple and mechanical thing to do to just add `&& execution(* *(..))` when converting a Spring AOP aspect to native AspectJ without breaking compatibility. The reason why you want to add that is to exclude AspectJ's `call()` joinpoints, which cause the double counts in your case. Spring AOP only knows `execution()`, i.e. there is is unnecessary. But AspectJ knows both pointcut types, which are semantically different - one is in call calling class/method, the other one in the called one.

org.springframework.aop.aspectj.annotation.AbstractAspectJAdvisorFactory#compiledByAjc

**Comment by kriegaex** [comment]
Another hint, just in case you happen to be using or be planning to use pointcuts with something like `within(my.package..*)`. Be careful there in native AspectJ, if the aspect is in the same package. In that case, add `&& !within(MyAspect)` to the pointcut to avoid the aspect from weaving itself or one aspect weaving the other one, which sometimes makes sense in AspectJ, but usually is not what you want. In Spring AOP, aspects cannot weave each other or themselves, i.e. it is implicitly excluded by the proxy-based approach, similar to how `call()` is not a thing due to the proxies.

**Comment by mihalyr** [comment]
Thank you Alexander, super useful information and the simpler syntax would solve binary compatibility issue I have also. 

> BTW, I tested a manually Ajc-compiled aspect in my old Spring AOP playground project with Spring 5.3.16 in the debugger, setting a breakpoint inside AbstractAspectJAdvisorFactory::compiledByAjc and each time forcing a return value of false, which made the native aspect work with Spring AOP. I guess, that is similar to your change for Spring 6.x., isn't it? I just wanted to make sure I understand this a bit better.

I can't comment on this part as it was @jhoeller who made that change in Spring, but I also assume it was something like that.

**Comment by marcingrzejszczak** [comment]
@kriegaex we're building micrometer with jdk11. Can we fix the AspectJ compiler to 1.9.20.1?

**Comment by marcingrzejszczak** [comment]
We would have to discuss this internally @shakuzen @jonatan-ivanov

**Comment by marcingrzejszczak** [comment]
Ok, https://github.com/micrometer-metrics/micrometer/pull/5059 is ready for review. Let's try to close this 5 year old issue ;)

**Comment by shakuzen** [comment]
This has been delivered in `1.14.0-SNAPSHOT` snapshots and for the upcoming `1.14.0-M1` milestone versions. Thank you to everyone who helped get this finally implemented.
Folks who were looking for this feature, let us know if it's working well for you or if there are any remaining issues.

**Comment by mihalyr** [comment]
I just found some time to test the snapshot briefly. I added the post-compile weaving Gradle plugin, removed the runtime javaagent and aop.xml from my project and checked that it builds and I get the metrics from the `@Timed` annotations on the `/prometheus` endpoint. 

First, I thought, something might be missing as `ajc` was giving me the warning of not applied aspect from the `TimedAspect.class`:

```
/var/home/tryprospect/.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.14.0-SNAPSHOT/9c4d0b30591b8215fd409ec80d50d624675f9aae/micrometer-core-1.14.0-SNAPSHOT.jar!io/micrometer/core/aop/TimedAspect.class [warning] advice defined in io.micrometer.core.aop.TimedAspect has not been applied [Xlint:adviceDidNotMatch]
```

But, I think, this was for the class-level annotation (`timedClass`) and I only use the method-level annotations, so the warning was a bit misleading without the pointcut. However, at runtime, I got the metrics, so I think, it is working. 

Before that, I tested also load-time weaving with the javaagent and was not getting the invalid pointcut syntax errors anymore at runtime, so that should be good too. 

What I don't use is Spring AOP, so I didn't test that.
