### ISSUE TITLE
Micrometer logs error message when partial error happens due to Infinity value using Elasticsearch

### ISSUE THREAD

**Issue by mmaia** [micrometer-metrics/micrometer#1370]
Micrometer core and  micrometer-elastic version: 1.1.3

Springboot version: 2.1.3.RELEASE

Hi, Using micrometer getting metrics from springboot application using `micrometer-registry-elastic` 

Micrometer keeps logging error messages: 

`ERROR [market-fetcher,,,] 8106 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : failed to send metrics to elastic:`   

When checking elastic index it's working, index get's updated with new values but I noticed one of the entries in there reports an error: 

`{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"XyEp_WkB2oH6K2ScUlT5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [value]","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}}`

which is probably what's causing the error log entry being generated. I guess it should instead be able to wrap / handle Infinity? Also not sure where the error is exactly from as we don't explicitly wrap any of the metrics in primitive float, still investigating that. 

Find below a  full entry of the log error message and pls let me know if it needs further details.

'2019-04-08 15:35:37.761 ERROR [market-fetcher,,,] 8106 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : failed to send metrics to elastic: {"took":24,"errors":true,"items":[{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"CCEp_WkB2oH6K2ScUlT5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":322,"_primary_term":1,"status":201}},{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"CSEp_WkB2oH6K2ScUlT5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":328,"_primary_term":1,"status":201}},
... 
,{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"XyEp_WkB2oH6K2ScUlT5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [value]","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}},{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"YCEp_WkB2oH6K2ScUlT5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":345,"_primary_term":1,"status":201}},{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"YSEp_WkB2oH6K2ScUlT5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":341,"_primary_term":1,"status":201}},
...
,{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"EiEp_WkB2oH6K2ScUlX6","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":383,"_primary_term":1,"status":201}}]}'

**Comment by izeye** [comment]
@mmaia Which version of Micrometer are you using? I expect it's been fixed since 1.1.2 thanks to #1135.

**Comment by mmaia** [comment]
> @mmaia Which version of Micrometer are you using? I expect it's been fixed since 1.1.2 thanks to #1135.

I've updated the issue to have the versions: 

Micrometer core and micrometer-elastic version: 1.1.3

Springboot version: 2.1.3.RELEASE

I am having a hard time tracing out which metric it is, any tips to make it easier to find out? We have dozens of metrics in this service so it's hard to track and I don't see any references to the specific metric that is failing. I could provide further details if you need, let me know what would be useful.

**Comment by izeye** [comment]
It seems to be possible for custom meters to supply infinity or NaN.

@mmaia Do you have any custom meter which could supply infinities? It'd be good to have a sample to reproduce this if possible. In the mean time I created #1373 to help track down the cause of this.

**Comment by izeye** [comment]
@mmaia As #1373 has been merged, it'd be good to try 1.1.5-SNAPSHOT and report back its request body if this happens again.

**Comment by izeye** [comment]
I created [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-1370) to reproduce this and got the following error:

```
2019-04-10 15:08:39.904 ERROR 15826 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : failed to send metrics to elastic: {"took":10,"errors":true,"items":[{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"P1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12831,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12832,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12901,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12902,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Q1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12506,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12864,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12865,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12507,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"R1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12833,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12508,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12509,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12834,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"S1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12866,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12510,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12835,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12511,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"T1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12836,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12512,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12513,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12791,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"U1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12903,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12867,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12837,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12792,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"V1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12793,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12794,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12838,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12868,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"W1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12795,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12869,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12870,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12871,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"X1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12904,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12514,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12905,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12839,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Y1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12840,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12906,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12907,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12872,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Z1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12796,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"aFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12908,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"aVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12515,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"alrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12841,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"a1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12873,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"bFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12842,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"bVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12874,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"blrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12909,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"b1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12843,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"cFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12875,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"cVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12844,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"clrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12845,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"c1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12516,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12797,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12876,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dlrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12910,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"d1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12877,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"eFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12798,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"eVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12911,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"elrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12799,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"e1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12517,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"fFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12878,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"fVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12879,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"flrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12912,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"f1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12846,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"gFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12913,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"gVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12518,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"glrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12880,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"g1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12519,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"hFrcBWoB8nnUV1ew1Wnt","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [value] of type [float]","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}}]}
```

I'm not sure it's the same cause as this issue but it's worth fixing regardless of it.

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/1374 to try to resolve this. If the proposed fix is okay, I'll prepare the similar fixes across all meter registries which drop non-finite values for publishing.

**Comment by mmaia** [comment]
> It seems to be possible for custom meters to supply infinity or NaN.
> 
> @mmaia Do you have any custom meter which could supply infinities? It'd be good to have a sample to reproduce this if possible. In the mean time I created #1373 to help track down the cause of this.

Yes, I get those from kafka client in producers and streams(which underlying wraps a consumer producer) when we get the metrics from them. It reports -Infinity and Infinity.

**Comment by mmaia** [comment]
> I created [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-1370) to reproduce this and got the following error:
> 
> ```
> 2019-04-10 15:08:39.904 ERROR 15826 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : failed to send metrics to elastic: {"took":10,"errors":true,"items":[{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"P1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12831,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12832,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12901,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"QlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12902,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Q1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12506,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12864,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12865,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"RlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12507,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"R1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12833,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12508,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12509,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"SlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12834,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"S1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12866,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12510,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12835,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"TlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12511,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"T1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12836,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12512,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12513,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"UlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12791,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"U1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12903,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12867,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12837,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"VlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12792,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"V1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12793,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12794,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12838,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"WlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12868,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"W1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12795,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12869,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12870,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"XlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12871,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"X1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12904,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12514,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12905,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"YlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12839,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Y1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12840,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12906,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12907,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"ZlrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12872,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"Z1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12796,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"aFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12908,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"aVrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12515,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"alrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12841,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"a1rcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12873,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"bFrcBWoB8nnUV1ew1Wns","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12842,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"bVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12874,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"blrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12909,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"b1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12843,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"cFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12875,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"cVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12844,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"clrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12845,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"c1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12516,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12797,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12876,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"dlrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12910,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"d1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12877,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"eFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12798,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"eVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12911,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"elrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12799,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"e1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12517,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"fFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12878,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"fVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12879,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"flrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12912,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"f1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12846,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"gFrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12913,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"gVrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12518,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"glrcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12880,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"g1rcBWoB8nnUV1ew1Wnt","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12519,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-04","_type":"doc","_id":"hFrcBWoB8nnUV1ew1Wnt","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [value] of type [float]","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}}]}
> ```
> I'm not sure it's the same cause as this issue but it's worth fixing regardless of it.

This looks exactly like the original error I posted indeed.

**Comment by shakuzen** [comment]
@mmaia would you try out 1.1.5-SNAPSHOT with the fix from @izeye to see if it resolves the issue you were facing?

**Comment by mmaia** [comment]
> @mmaia would you try out 1.1.5-SNAPSHOT with the fix from @izeye to see if it resolves the issue you were facing?

sure, will do it now and get back to you here.

**Comment by mmaia** [comment]
@shakuzen - where should I get it from? I can't find a tag. Should I built it from branch 1.1.x?

**Comment by izeye** [comment]
@mmaia See the following configuration: https://github.com/izeye/sample-micrometer-spring-boot/blob/micrometer-gh-1370/build.gradle#L23-L39

**Comment by shakuzen** [comment]
As @izeye's sample shows, you just need to add to your build configuration the repository that we publish snapshots to (`https://repo.spring.io/libs-snapshot`) and then use the snapshot version `1.1.5-SNAPSHOT`.
https://github.com/micrometer-metrics/micrometer#snapshot-builds

**Comment by mmaia** [comment]
Hi guys, firs of all thank you for the quick support. 

Unfortunately I am still having the issue. I took my time to test it to be sure. Here's the entry in a dependence tree(I use maven)...
```
[INFO] nl.ing.securities:market-fetcher:jar:ANY-SNAPSHOT
[INFO] +- io.micrometer:micrometer-registry-elastic:jar:1.1.5-SNAPSHOT:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.1.3:compile
```

The only strange thing is that 1.1.5 snapshot is bringing core 1.1.3. And in this setup the error still persists. 

```
2019-04-12 08:59:48.617 ERROR [market-fetcher,,,] 38326 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : failed to send metrics to elastic: {"took":24,"errors":true,"items":[ ...
{"index":{"_index":"market-fetcher-metrics-2019-04","_type":"doc","_id":"8jBXEGoBuMT_3_FLdmBb","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [value]","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}}

...
```

I will force core to also be in 1.1.5-SNAPSHOT and test it also, keep you posted.

**Comment by izeye** [comment]
@mmaia To have consistent versions, you need to set the following property and drop version(s) on Micrometer dependencies if any to let Spring Boot manage versions for you:

```
<properties>
	<micrometer.version>1.1.5-SNAPSHOT</micrometer.version>
</properties>
```

As the fix lives in the `micrometer-registry-elastic` artifact, if the cause was the same, it should be fixed regardless of the version of the `micrometer-core` artifact.

Could you provide the request body by enabling debug-level logging against `io.micrometer.elastic` if this happens again?

**Comment by mmaia** [comment]
Yes, I've tested with core also in snapshot and indeed same issue still there. It still looks the same: `[float] supports only finite values, but got [Infinity]`
 
I have also enabled debugging and only debug messages I got was a successfully sent(possibly in that case no Infinity was reported) and whenever there's Infinity in there the error pops up again: 

<img width="1327" alt="Screen Shot 2019-04-12 at 09 36 03" src="https://user-images.githubusercontent.com/145428/56020503-98218a80-5d07-11e9-8435-e0fa409ffaaa.png">

I will enable debugging in the elastic client see If I get some extra info there, is that what you meant?

**Comment by izeye** [comment]
I expected the following debug log with the error log you were seeing if you have a correct snapshot: https://github.com/micrometer-metrics/micrometer/blob/1.1.x/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java#L165

You can check whether you have a correct one by opening the source of the `ElasticMeterRegistry` in your IDE and seeing that the debug log line is included there.

**Comment by mmaia** [comment]
@izeye - I will have to blame IntelliJ for this one, after you pointed to the debug line I double check with the dependency tree and the version was correct 1.1.5-SNAPSHOT then I did a full: "Invalidate Caches / Restart" (damn IntelliJ) and after that it just works, sorry for the misleading message. It looks fixed indeed, great work. Thank you. 

<img width="1195" alt="Screen Shot 2019-04-12 at 11 24 10" src="https://user-images.githubusercontent.com/145428/56027213-e5a4f400-5d15-11e9-99b3-a1c40ece2873.png">

**Comment by izeye** [comment]
@mmaia Thanks for confirming the fix :+1:

**Comment by sabareeshkkanan** [comment]
I am still facing this issue even with the new snapshot. It produced several metric where elastic might consider it as not finite. 
Spring boot 2.1.4
Spring cloud GreenwichSR1
Java11
Spring Cloud Kafka Streams

```
+--- io.micrometer:micrometer-registry-elastic:1.1.5-SNAPSHOT
|    \--- io.micrometer:micrometer-core:1.1.5-SNAPSHOT (*)

```


```
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"0","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"1","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"2","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"3","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"4","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"5","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"6","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"7","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
```

**Comment by CakeSpork** [comment]
I'm having the exact same issue as @sabareeshkkanan above - with the same kafka_consumer_records* fields with MAX_DOUBLE being somehow treated as 'infinite'.

Running under Spring boot 2.1.7.RELEASE with Greenwich.SR2 cloud dependencies and
io.micrometer:micrometer-core:jar:1.1.5:compile
io.micrometer:micrometer-registry-elastic:jar:1.2.0:compile

**Comment by shakuzen** [comment]
@CakeSpork have you seen the note in the release note about deleting the template so the fixed template can be configured? https://github.com/micrometer-metrics/micrometer/releases/tag/v1.1.5

**Comment by izeye** [comment]
@CakeSpork I can see you’re using mixed versions of Micrometer. You’d better use a consistent version to avoid potential incompatibilities.

**Comment by CakeSpork** [comment]
@izeye this was because the 1.2.0 release had some issues - they seem to be resolved in 1.2.1. But you're right that I could've used 1.1.5 registry-elastic.

@shakuzen I missed that - but I have to find out more about the metrics_template
